# Generated by Django 4.1.3 on 2023-10-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_otp_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
