# Generated by Django 4.1.3 on 2023-10-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_func', '0003_user_achievements_user_faculty_user_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
