# Generated by Django 4.1.3 on 2023-10-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_func', '0004_user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
