# Generated by Django 4.1.3 on 2023-10-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_func', '0006_accesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='created_at',
        ),
    ]
