# Generated by Django 4.1.3 on 2023-10-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_func', '0007_remove_accesstoken_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
