# Generated by Django 4.1.3 on 2023-10-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_func', '0008_user_access_token_user_refresh_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
