# Generated by Django 4.1.3 on 2023-10-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_func', '0010_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
