# Generated by Django 4.1.3 on 2023-10-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_func', '0002_remove_news_image_news_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='news_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
